version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_rest_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    image: maven:3.9.8-eclipse-temurin-21
    container_name: bank-rest-app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank_rest_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      BANK_REST_APP_SECRET: u8g9VJ6k2nO3pQ1rX4yZ0aWbE5tVxYzB2cAqHjKlMnP=
      BANK_REST_APP_EXPIRATIONMS: 3600000
      BANK_REST_APP_REFRESH_EXPIRATION: 86400000
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "mvn spring-boot:run"

volumes:
  mysql-data:
