server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_rest_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/migration/master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#Jwt Configuration
bank_rest:
  app:
    secret: u8g9VJ6k2nO3pQ1rX4yZ0aWbE5tVxYzB2cAqHjKlMnP=
    expirationMs: 3600000
    refresh-expiration: 86400000



## application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

