server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_rest_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/migration/master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui
    url: /openapi-docs/openapi.yml
  api-docs:
    path: /openapi/api-docs

#Jwt Configuration
bank-rest:
  app:
    secret: ${APP_JWT_SECRET}
    expirationMs: 3600000
    refresh-expiration: 86400000

